### ISSUE TITLE
Suggestion + appreciation post.

### ISSUE THREAD

**Issue by ghost** [mt025/twitch-drops-lurker#1]
Hello mt025, 

I've been following this fork for a week now. And it's very good! Very easy to configure & customize. Well, a suggestion that I've for this fork it's to add an auto-redeem channel points & also, an idler variable in index.js to search a streamer to watch without specifying game, just to watch it directly & farm.

If it's something that you don't want or you want to change something in it. Let me know!

**Comment by mt025** [comment]
Thanks! I will look into channel points. I do have a browser script to do that already, so I think it won't be too taxing.

In the next couple of days I will be working on creating idlers from the web interface, as the index.js settings are just a temporary. I will make sure that you can idle a streamer without specifiying a game.

**Comment by ghost** [comment]
Thanks for taking your time for responding! But I've got another issue that maybe it's not linked with the repo itself but I want to get it fixed, how to do I update the cloned repo without cloning it again?

**Comment by mt025** [comment]
`git pull` - to update the repo and attempt to merge any changes that you have made, If there are merge conflicts and you just want to keep the repo code  use `git reset --hard origin/master` - to drop any changes that you have made.

**Comment by rlith** [comment]
Okay, thanks! One last thing, do you have like a discord or something?

**Comment by mt025** [comment]
MagicTree#3151

**Comment by mt025** [comment]
Updated! Please check [README.md](https://github.com/mt025/twitch-drops-lurker/blob/master/README.md) for info!
