### ISSUE TITLE
Issue with Legacy type idler.

### ISSUE THREAD

**Issue by ghost** [mt025/twitch-drops-lurker#2]
Hello,

There's an issue with the idler on Legacy type that, whenever I use it on games like R6S doesn't find stream but there is streams with drops enabled, and so I try stopping the process and works. Other way that provokes that issue is; idler goes for 1 hour, changes stream and doesn't find anyone. And so the same way to fix it, restarting process.

Can you fix it so I don't have to restart the process everytime it happens?

**Comment by mt025** [comment]
It should automatically change to a new streamer within 60 seconds. Otherwise you can click the next streamer button In the Web interface to go next right away. I will look into searching for a stream with drops enabled but I'm not sure that is currently possible.

**Comment by mt025** [comment]
Do you get any errors in your console? Are you able to post `userlogins/users.json`

**Comment by ghost** [comment]
Okay, I'll post it right now. The errors that I get in console are like, couldn't find a streamer, searching again & loops.
`[{"name":"streamer","game":"Tom Clancy's Rainbow Six Siege","type":"legacy","account":"autiv","autostart":true,"channelPoints":true,"streamerList":[]}]`

**Comment by mt025** [comment]
Okay well I can't replicate the issue on the platforms I have. However I have added additional checks to give the browser time to load the streamers list page. Try the latest commit.

**Comment by rlith** [comment]
Thank you, already updated the repo. If the issue persists, I'll let you know.

**Comment by ghost** [comment]
Thank you, already updated the repo. If the issue persists, I'll let you know.
