### ISSUE TITLE
Suggestion (not that necessary but I'll just throw it away).

### ISSUE THREAD

**Issue by ghost** [mt025/twitch-drops-lurker#3]
Hello again,

This one may be little complicated, but I'm just gonna post it here if someday becomes relevant. 
Ability to schedule idler to watch certain game, for example, to stop watching one game for drops & to switch to another that is scheduled for 9 PM & to end after 3 hours, for example, 12 PM.

Anyways, you're doing a great job with this project!

**Comment by mt025** [comment]
Its a nice idea. I'll keep it in mind.
